const countryMap = {
  "アフガニスタン": { en: "Afghanistan", code: "AF", code3: "AFG", capital: "カブール", currency: "アフガニ", currencyCode: "AFN", currencySymbol: "؋" },
  "アルバニア": { en: "Albania", code: "AL", code3: "ALB", capital: "ティラナ", currency: "レク", currencyCode: "ALL", currencySymbol: "L" },
  "アルジェリア": { en: "Algeria", code: "DZ", code3: "DZA", capital: "アルジェ", currency: "アルジェリア・ディナール", currencyCode: "DZD", currencySymbol: "د.ج" },
  "アンドラ": { en: "Andorra", code: "AD", code3: "AND", capital: "アンドラ・ラ・ベリャ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "アンゴラ": { en: "Angola", code: "AO", code3: "AGO", capital: "ルアンダ", currency: "クワンザ", currencyCode: "AOA", currencySymbol: "Kz" },
  "アンティグア・バーブーダ": { en: "Antigua and Barbuda", code: "AG", code3: "ATG", capital: "セントジョンズ", currency: "東カリブ・ドル", currencyCode: "XCD", currencySymbol: "$" },
  "アルゼンチン": { en: "Argentina", code: "AR", code3: "ARG", capital: "ブエノスアイレス", currency: "アルゼンチン・ペソ", currencyCode: "ARS", currencySymbol: "$" },
  "アルメニア": { en: "Armenia", code: "AM", code3: "ARM", capital: "エレバン", currency: "ドラム", currencyCode: "AMD", currencySymbol: "֏" },
  "オーストラリア": { en: "Australia", code: "AU", code3: "AUS", capital: "キャンベラ", currency: "オーストラリア・ドル", currencyCode: "AUD", currencySymbol: "$" },
  "オーストリア": { en: "Austria", code: "AT", code3: "AUT", capital: "ウィーン", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "アゼルバイジャン": { en: "Azerbaijan", code: "AZ", code3: "AZE", capital: "バクー", currency: "アゼルバイジャン・マナト", currencyCode: "AZN", currencySymbol: "₼" },
  "バハマ": { en: "Bahamas", code: "BS", code3: "BHS", capital: "ナッソー", currency: "バハマ・ドル", currencyCode: "BSD", currencySymbol: "$" },
  "バーレーン": { en: "Bahrain", code: "BH", code3: "BHR", capital: "マナーマ", currency: "バーレーン・ディナール", currencyCode: "BHD", currencySymbol: ".د.ب" },
  "バングラデシュ": { en: "Bangladesh", code: "BD", code3: "BGD", capital: "ダッカ", currency: "タカ", currencyCode: "BDT", currencySymbol: "৳" },
  "バルバドス": { en: "Barbados", code: "BB", code3: "BRB", capital: "ブリッジタウン", currency: "バルバドス・ドル", currencyCode: "BBD", currencySymbol: "$" },
  "ベラルーシ": { en: "Belarus", code: "BY", code3: "BLR", capital: "ミンスク", currency: "ベラルーシ・ルーブル", currencyCode: "BYN", currencySymbol: "Br" },
  "ベルギー": { en: "Belgium", code: "BE", code3: "BEL", capital: "ブリュッセル", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ベリーズ": { en: "Belize", code: "BZ", code3: "BLZ", capital: "ベルモパン", currency: "ベリーズ・ドル", currencyCode: "BZD", currencySymbol: "$" },
  "ベナン": { en: "Benin", code: "BJ", code3: "BEN", capital: "ポルトノボ", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "ブータン": { en: "Bhutan", code: "BT", code3: "BTN", capital: "ティンプー", currency: "ニュルタム", currencyCode: "BTN", currencySymbol: "Nu." },
  "ボリビア": { en: "Bolivia", code: "BO", code3: "BOL", capital: "スクレ", currency: "ボリビアーノ", currencyCode: "BOB", currencySymbol: "Bs." },
  "ボスニア・ヘルツェゴビナ": { en: "Bosnia and Herzegovina", code: "BA", code3: "BIH", capital: "サラエボ", currency: "兌換マルク", currencyCode: "BAM", currencySymbol: "KM" },
  "ボツワナ": { en: "Botswana", code: "BW", code3: "BWA", capital: "ハボローネ", currency: "プラ", currencyCode: "BWP", currencySymbol: "P" },
  "ブラジル": { en: "Brazil", code: "BR", code3: "BRA", capital: "ブラジリア", currency: "レアル", currencyCode: "BRL", currencySymbol: "R$" },
  "ブルネイ": { en: "Brunei", code: "BN", code3: "BRN", capital: "バンダルスリブガワン", currency: "ブルネイ・ドル", currencyCode: "BND", currencySymbol: "$" },
  "ブルガリア": { en: "Bulgaria", code: "BG", code3: "BGR", capital: "ソフィア", currency: "レフ", currencyCode: "BGN", currencySymbol: "лв" },
  "ブルキナファソ": { en: "Burkina Faso", code: "BF", code3: "BFA", capital: "ワガドゥグー", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "ブルンジ": { en: "Burundi", code: "BI", code3: "BDI", capital: "ギテガ", currency: "ブルンジ・フラン", currencyCode: "BIF", currencySymbol: "Fr" },
  "カーボベルデ": { en: "Cabo Verde", code: "CV", code3: "CPV", capital: "プライア", currency: "カーボベルデ・エスクード", currencyCode: "CVE", currencySymbol: "Esc" },
  "カンボジア": { en: "Cambodia", code: "KH", code3: "KHM", capital: "プノンペン", currency: "リエル", currencyCode: "KHR", currencySymbol: "៛" },
  "カメルーン": { en: "Cameroon", code: "CM", code3: "CMR", capital: "ヤウンデ", currency: "CFAフラン", currencyCode: "XAF", currencySymbol: "Fr" },
  "カナダ": { en: "Canada", code: "CA", code3: "CAN", capital: "オタワ", currency: "カナダ・ドル", currencyCode: "CAD", currencySymbol: "$" },
  "中央アフリカ": { en: "Central African Republic", code: "CF", code3: "CAF", capital: "バンギ", currency: "CFAフラン", currencyCode: "XAF", currencySymbol: "Fr" },
  "チャド": { en: "Chad", code: "TD", code3: "TCD", capital: "ンジャメナ", currency: "CFAフラン", currencyCode: "XAF", currencySymbol: "Fr" },
  "チリ": { en: "Chile", code: "CL", code3: "CHL", capital: "サンティアゴ", currency: "チリ・ペソ", currencyCode: "CLP", currencySymbol: "$" },
  "中国": { en: "China", code: "CN", code3: "CHN", capital: "北京", currency: "人民元", currencyCode: "CNY", currencySymbol: "¥" },
  "コロンビア": { en: "Colombia", code: "CO", code3: "COL", capital: "ボゴタ", currency: "コロンビア・ペソ", currencyCode: "COP", currencySymbol: "$" },
  "コモロ": { en: "Comoros", code: "KM", code3: "COM", capital: "モロニ", currency: "コモロ・フラン", currencyCode: "KMF", currencySymbol: "Fr" },
  "コンゴ共和国": { en: "Congo", code: "CG", code3: "COG", capital: "ブラザビル", currency: "CFAフラン", currencyCode: "XAF", currencySymbol: "Fr" },
  "コンゴ民主共和国": { en: "Democratic Republic of the Congo", code: "CD", code3: "COD", capital: "キンシャサ", currency: "コンゴ・フラン", currencyCode: "CDF", currencySymbol: "Fr" },
  "コスタリカ": { en: "Costa Rica", code: "CR", code3: "CRC", capital: "サンホセ", currency: "コスタリカ・コロン", currencyCode: "CRC", currencySymbol: "₡" },
  "コートジボワール": { en: "Cote d'Ivoire", code: "CI", code3: "CIV", capital: "ヤムスクロ", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "クロアチア": { en: "Croatia", code: "HR", code3: "HRV", capital: "ザグレブ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "キューバ": { en: "Cuba", code: "CU", code3: "CUB", capital: "ハバナ", currency: "キューバ・ペソ", currencyCode: "CUP", currencySymbol: "$" },
  "キプロス": { en: "Cyprus", code: "CY", code3: "CYP", capital: "ニコシア", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "チェコ": { en: "Czech Republic", code: "CZ", code3: "CZE", capital: "プラハ", currency: "チェコ・コルナ", currencyCode: "CZK", currencySymbol: "Kč" },
  "デンマーク": { en: "Denmark", code: "DK", code3: "DNK", capital: "コペンハーゲン", currency: "デンマーク・クローネ", currencyCode: "DKK", currencySymbol: "kr" },
  "ジブチ": { en: "Djibouti", code: "DJ", code3: "DJI", capital: "ジブチ", currency: "ジブチ・フラン", currencyCode: "DJF", currencySymbol: "Fr" },
  "ドミニカ国": { en: "Dominica", code: "DM", code3: "DMA", capital: "ロゾー", currency: "東カリブ・ドル", currencyCode: "XCD", currencySymbol: "$" },
  "ドミニカ共和国": { en: "Dominican Republic", code: "DO", code3: "DOM", capital: "サントドミンゴ", currency: "ドミニカ・ペソ", currencyCode: "DOP", currencySymbol: "$" },
  "エクアドル": { en: "Ecuador", code: "EC", code3: "ECU", capital: "キト", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "エジプト": { en: "Egypt", code: "EG", code3: "EGY", capital: "カイロ", currency: "エジプト・ポンド", currencyCode: "EGP", currencySymbol: "E£" },
  "エルサルバドル": { en: "El Salvador", code: "SV", code3: "SLV", capital: "サンサルバドル", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "赤道ギニア": { en: "Equatorial Guinea", code: "GQ", code3: "GNQ", capital: "マラボ", currency: "CFAフラン", currencyCode: "XAF", currencySymbol: "Fr" },
  "エリトリア": { en: "Eritrea", code: "ER", code3: "ERI", capital: "アスマラ", currency: "ナクファ", currencyCode: "ERN", currencySymbol: "Nfk" },
  "エストニア": { en: "Estonia", code: "EE", code3: "EST", capital: "タリン", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "エスワティニ": { en: "Eswatini", code: "SZ", code3: "SWZ", capital: "ムババーネ", currency: "リランゲニ", currencyCode: "SZL", currencySymbol: "L" },
  "エチオピア": { en: "Ethiopia", code: "ET", code3: "ETH", capital: "アディスアベバ", currency: "ブル", currencyCode: "ETB", currencySymbol: "Br" },
  "フィジー": { en: "Fiji", code: "FJ", code3: "FJI", capital: "スバ", currency: "フィジー・ドル", currencyCode: "FJD", currencySymbol: "$" },
  "フィンランド": { en: "Finland", code: "FI", code3: "FIN", capital: "ヘルシンキ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "フランス": { en: "France", code: "FR", code3: "FRA", capital: "パリ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ガボン": { en: "Gabon", code: "GA", code3: "GAB", capital: "リーブルビル", currency: "CFAフラン", currencyCode: "XAF", currencySymbol: "Fr" },
  "ガンビア": { en: "Gambia", code: "GM", code3: "GMB", capital: "バンジュール", currency: "ダラシ", currencyCode: "GMD", currencySymbol: "D" },
  "ジョージア": { en: "Georgia", code: "GE", code3: "GEO", capital: "トビリシ", currency: "ラリ", currencyCode: "GEL", currencySymbol: "₾" },
  "ドイツ": { en: "Germany", code: "DE", code3: "DEU", capital: "ベルリン", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ガーナ": { en: "Ghana", code: "GH", code3: "GHA", capital: "アクラ", currency: "セディ", currencyCode: "GHS", currencySymbol: "₵" },
  "ギリシャ": { en: "Greece", code: "GR", code3: "GRC", capital: "アテネ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "グレナダ": { en: "Grenada", code: "GD", code3: "GRD", capital: "セントジョージズ", currency: "東カリブ・ドル", currencyCode: "XCD", currencySymbol: "$" },
  "グアテマラ": { en: "Guatemala", code: "GT", code3: "GTM", capital: "グアテマラシティ", currency: "ケツァル", currencyCode: "GTQ", currencySymbol: "Q" },
  "ギニア": { en: "Guinea", code: "GN", code3: "GIN", capital: "コナクリ", currency: "ギニア・フラン", currencyCode: "GNF", currencySymbol: "Fr" },
  "ギニアビサウ": { en: "Guinea-Bissau", code: "GW", code3: "GNB", capital: "ビサウ", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "ガイアナ": { en: "Guyana", code: "GY", code3: "GUY", capital: "ジョージタウン", currency: "ガイアナ・ドル", currencyCode: "GYD", currencySymbol: "$" },
  "ハイチ": { en: "Haiti", code: "HT", code3: "HTI", capital: "ポルトープランス", currency: "グールド", currencyCode: "HTG", currencySymbol: "G" },
  "ホンジュラス": { en: "Honduras", code: "HN", code3: "HND", capital: "テグシガルパ", currency: "レンピラ", currencyCode: "HNL", currencySymbol: "L" },
  "ハンガリー": { en: "Hungary", code: "HU", code3: "HUN", capital: "ブダペスト", currency: "フォリント", currencyCode: "HUF", currencySymbol: "Ft" },
  "アイスランド": { en: "Iceland", code: "IS", code3: "ISL", capital: "レイキャビク", currency: "アイスランド・クローナ", currencyCode: "ISK", currencySymbol: "kr" },
  "インド": { en: "India", code: "IN", code3: "IND", capital: "ニューデリー", currency: "インド・ルピー", currencyCode: "INR", currencySymbol: "₹" },
  "インドネシア": { en: "Indonesia", code: "ID", code3: "IDN", capital: "ジャカルタ", currency: "ルピア", currencyCode: "IDR", currencySymbol: "Rp" },
  "イラン": { en: "Iran", code: "IR", code3: "IRN", capital: "テヘラン", currency: "イラン・リアル", currencyCode: "IRR", currencySymbol: "﷼" },
  "イラク": { en: "Iraq", code: "IQ", code3: "IRQ", capital: "バグダッド", currency: "イラク・ディナール", currencyCode: "IQD", currencySymbol: "ع.د" },
  "アイルランド": { en: "Ireland", code: "IE", code3: "IRL", capital: "ダブリン", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "イスラエル": { en: "Israel", code: "IL", code3: "ISR", capital: "エルサレム", currency: "新シェケル", currencyCode: "ILS", currencySymbol: "₪" },
  "イタリア": { en: "Italy", code: "IT", code3: "ITA", capital: "ローマ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ジャマイカ": { en: "Jamaica", code: "JM", code3: "JAM", capital: "キングストン", currency: "ジャマイカ・ドル", currencyCode: "JMD", currencySymbol: "$" },
  "日本": { en: "Japan", code: "JP", code3: "JPN", capital: "東京", isJapan: true, currency: "日本円", currencyCode: "JPY", currencySymbol: "¥" },
  "ヨルダン": { en: "Jordan", code: "JO", code3: "JOR", capital: "アンマン", currency: "ヨルダン・ディナール", currencyCode: "JOD", currencySymbol: "د.أ" },
  "カザフスタン": { en: "Kazakhstan", code: "KZ", code3: "KAZ", capital: "アスタナ", currency: "テンゲ", currencyCode: "KZT", currencySymbol: "₸" },
  "ケニア": { en: "Kenya", code: "KE", code3: "KEN", capital: "ナイロビ", currency: "ケニア・シリング", currencyCode: "KES", currencySymbol: "Sh" },
  "キリバス": { en: "Kiribati", code: "KI", code3: "KIR", capital: "タラワ", currency: "オーストラリア・ドル", currencyCode: "AUD", currencySymbol: "$" },
  "クウェート": { en: "Kuwait", code: "KW", code3: "KWT", capital: "クウェートシティ", currency: "クウェート・ディナール", currencyCode: "KWD", currencySymbol: "د.ك" },
  "キルギス": { en: "Kyrgyzstan", code: "KG", code3: "KGZ", capital: "ビシュケク", currency: "ソム", currencyCode: "KGS", currencySymbol: "с" },
  "ラオス": { en: "Laos", code: "LA", code3: "LAO", capital: "ビエンチャン", currency: "キップ", currencyCode: "LAK", currencySymbol: "₭" },
  "ラトビア": { en: "Latvia", code: "LV", code3: "LVA", capital: "リガ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "レバノン": { en: "Lebanon", code: "LB", code3: "LBN", capital: "ベイルート", currency: "レバノン・ポンド", currencyCode: "LBP", currencySymbol: "ل.ل" },
  "レソト": { en: "Lesotho", code: "LS", code3: "LSO", capital: "マセル", currency: "ロチ", currencyCode: "LSL", currencySymbol: "L" },
  "リベリア": { en: "Liberia", code: "LR", code3: "LBR", capital: "モンロビア", currency: "リベリア・ドル", currencyCode: "LRD", currencySymbol: "$" },
  "リビア": { en: "Libya", code: "LY", code3: "LBY", capital: "トリポリ", currency: "リビア・ディナール", currencyCode: "LYD", currencySymbol: "ل.د" },
  "リヒテンシュタイン": { en: "Liechtenstein", code: "LI", code3: "LIE", capital: "ファドゥーツ", currency: "スイス・フラン", currencyCode: "CHF", currencySymbol: "Fr" },
  "リトアニア": { en: "Lithuania", code: "LT", code3: "LTU", capital: "ビリニュス", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ルクセンブルク": { en: "Luxembourg", code: "LU", code3: "LUX", capital: "ルクセンブルク", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "マダガスカル": { en: "Madagascar", code: "MG", code3: "MDG", capital: "アンタナナリボ", currency: "アリアリ", currencyCode: "MGA", currencySymbol: "Ar" },
  "マラウイ": { en: "Malawi", code: "MW", code3: "MWI", capital: "リロングウェ", currency: "クワチャ", currencyCode: "MWK", currencySymbol: "MK" },
  "マレーシア": { en: "Malaysia", code: "MY", code3: "MYS", capital: "クアラルンプール", currency: "リンギット", currencyCode: "MYR", currencySymbol: "RM" },
  "モルディブ": { en: "Maldives", code: "MV", code3: "MDV", capital: "マレ", currency: "ルフィヤ", currencyCode: "MVR", currencySymbol: ".ރ" },
  "マリ": { en: "Mali", code: "ML", code3: "MLI", capital: "バマコ", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "マルタ": { en: "Malta", code: "MT", code3: "MLT", capital: "バレッタ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "マーシャル諸島": { en: "Marshall Islands", code: "MH", code3: "MHL", capital: "マジュロ", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "モーリタニア": { en: "Mauritania", code: "MR", code3: "MRT", capital: "ヌアクショット", currency: "ウギア", currencyCode: "MRU", currencySymbol: "UM" },
  "モーリシャス": { en: "Mauritius", code: "MU", code3: "MUS", capital: "ポートルイス", currency: "モーリシャス・ルピー", currencyCode: "MUR", currencySymbol: "₨" },
  "メキシコ": { en: "Mexico", code: "MX", code3: "MEX", capital: "メキシコシティ", currency: "メキシコ・ペソ", currencyCode: "MXN", currencySymbol: "$" },
  "ミクロネシア連邦": { en: "Micronesia", code: "FM", code3: "FSM", capital: "パリキール", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "モルドバ": { en: "Moldova", code: "MD", code3: "MDA", capital: "キシナウ", currency: "モルドバ・レウ", currencyCode: "MDL", currencySymbol: "L" },
  "モナコ": { en: "Monaco", code: "MC", code3: "MCO", capital: "モナコ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "モンゴル": { en: "Mongolia", code: "MN", code3: "MNG", capital: "ウランバートル", currency: "トゥグルグ", currencyCode: "MNT", currencySymbol: "₮" },
  "モンテネグロ": { en: "Montenegro", code: "ME", code3: "MNE", capital: "ポドゴリツァ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "モロッコ": { en: "Morocco", code: "MA", code3: "MAR", capital: "ラバト", currency: "モロッコ・ディルハム", currencyCode: "MAD", currencySymbol: "د.م." },
  "モザンビーク": { en: "Mozambique", code: "MZ", code3: "MOZ", capital: "マプト", currency: "メティカル", currencyCode: "MZN", currencySymbol: "MT" },
  "ミャンマー": { en: "Myanmar", code: "MM", code3: "MMR", capital: "ネーピードー", currency: "チャット", currencyCode: "MMK", currencySymbol: "Ks" },
  "ナミビア": { en: "Namibia", code: "NA", code3: "NAM", capital: "ウィントフック", currency: "ナミビア・ドル", currencyCode: "NAD", currencySymbol: "$" },
  "ナウル": { en: "Nauru", code: "NR", code3: "NRU", capital: "ヤレン", currency: "オーストラリア・ドル", currencyCode: "AUD", currencySymbol: "$" },
  "ネパール": { en: "Nepal", code: "NP", code3: "NPL", capital: "カトマンズ", currency: "ネパール・ルピー", currencyCode: "NPR", currencySymbol: "₨" },
  "オランダ": { en: "Netherlands", code: "NL", code3: "NLD", capital: "アムステルダム", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ニュージーランド": { en: "New Zealand", code: "NZ", code3: "NZL", capital: "ウェリントン", currency: "ニュージーランド・ドル", currencyCode: "NZD", currencySymbol: "$" },
  "ニカラグア": { en: "Nicaragua", code: "NI", code3: "NIC", capital: "マナグア", currency: "コルドバ", currencyCode: "NIO", currencySymbol: "C$" },
  "ニジェール": { en: "Niger", code: "NE", code3: "NER", capital: "ニアメ", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "ナイジェリア": { en: "Nigeria", code: "NG", code3: "NGA", capital: "アブジャ", currency: "ナイラ", currencyCode: "NGN", currencySymbol: "₦" },
  "北朝鮮": { en: "North Korea", code: "KP", code3: "PRK", capital: "平壌", currency: "北朝鮮ウォン", currencyCode: "KPW", currencySymbol: "₩" },
  "北マケドニア": { en: "North Macedonia", code: "MK", code3: "MKD", capital: "スコピエ", currency: "デナール", currencyCode: "MKD", currencySymbol: "ден" },
  "ノルウェー": { en: "Norway", code: "NO", code3: "NOR", capital: "オスロ", currency: "ノルウェー・クローネ", currencyCode: "NOK", currencySymbol: "kr" },
  "オマーン": { en: "Oman", code: "OM", code3: "OMN", capital: "マスカット", currency: "オマーン・リアル", currencyCode: "OMR", currencySymbol: "ر.ع." },
  "パキスタン": { en: "Pakistan", code: "PK", code3: "PAK", capital: "イスラマバード", currency: "パキスタン・ルピー", currencyCode: "PKR", currencySymbol: "₨" },
  "パラオ": { en: "Palau", code: "PW", code3: "PLW", capital: "ンゲルルムッド", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "パナマ": { en: "Panama", code: "PA", code3: "PAN", capital: "パナマシティ", currency: "バルボア", currencyCode: "PAB", currencySymbol: "B/." },
  "パプアニューギニア": { en: "Papua New Guinea", code: "PG", code3: "PNG", capital: "ポートモレスビー", currency: "キナ", currencyCode: "PGK", currencySymbol: "K" },
  "パラグアイ": { en: "Paraguay", code: "PY", code3: "PRY", capital: "アスンシオン", currency: "グアラニー", currencyCode: "PYG", currencySymbol: "₲" },
  "ペルー": { en: "Peru", code: "PE", code3: "PER", capital: "リマ", currency: "ソル", currencyCode: "PEN", currencySymbol: "S/." },
  "フィリピン": { en: "Philippines", code: "PH", code3: "PHL", capital: "マニラ", currency: "フィリピン・ペソ", currencyCode: "PHP", currencySymbol: "₱" },
  "ポーランド": { en: "Poland", code: "PL", code3: "POL", capital: "ワルシャワ", currency: "ズウォティ", currencyCode: "PLN", currencySymbol: "zł" },
  "ポルトガル": { en: "Portugal", code: "PT", code3: "PRT", capital: "リスボン", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "カタール": { en: "Qatar", code: "QA", code3: "QAT", capital: "ドーハ", currency: "カタール・リアル", currencyCode: "QAR", currencySymbol: "ر.ق" },
  "ルーマニア": { en: "Romania", code: "RO", code3: "ROU", capital: "ブカレスト", currency: "ルーマニア・レウ", currencyCode: "RON", currencySymbol: "lei" },
  "ロシア": { en: "Russia", code: "RU", code3: "RUS", capital: "モスクワ", currency: "ロシア・ルーブル", currencyCode: "RUB", currencySymbol: "₽" },
  "ルワンダ": { en: "Rwanda", code: "RW", code3: "RWA", capital: "キガリ", currency: "ルワンダ・フラン", currencyCode: "RWF", currencySymbol: "Fr" },
  "セントクリストファー・ネービス": { en: "Saint Kitts and Nevis", code: "KN", code3: "KNA", capital: "バセテール", currency: "東カリブ・ドル", currencyCode: "XCD", currencySymbol: "$" },
  "セントルシア": { en: "Saint Lucia", code: "LC", code3: "LCA", capital: "カストリーズ", currency: "東カリブ・ドル", currencyCode: "XCD", currencySymbol: "$" },
  "セントビンセント・グレナディーン": { en: "Saint Vincent and the Grenadines", code: "VC", code3: "VCT", capital: "キングスタウン", currency: "東カリブ・ドル", currencyCode: "XCD", currencySymbol: "$" },
  "サモア": { en: "Samoa", code: "WS", code3: "WSM", capital: "アピア", currency: "タラ", currencyCode: "WST", currencySymbol: "T" },
  "サンマリノ": { en: "San Marino", code: "SM", code3: "SMR", capital: "サンマリノ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "サントメ・プリンシペ": { en: "Sao Tome and Principe", code: "ST", code3: "STP", capital: "サントメ", currency: "ドブラ", currencyCode: "STN", currencySymbol: "Db" },
  "サウジアラビア": { en: "Saudi Arabia", code: "SA", code3: "SAU", capital: "リヤド", currency: "サウジ・リアル", currencyCode: "SAR", currencySymbol: "ر.س" },
  "セネガル": { en: "Senegal", code: "SN", code3: "SEN", capital: "ダカール", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "セルビア": { en: "Serbia", code: "RS", code3: "SRB", capital: "ベオグラード", currency: "セルビア・ディナール", currencyCode: "RSD", currencySymbol: "дин." },
  "セーシェル": { en: "Seychelles", code: "SC", code3: "SYC", capital: "ビクトリア", currency: "セーシェル・ルピー", currencyCode: "SCR", currencySymbol: "₨" },
  "シエラレオネ": { en: "Sierra Leone", code: "SL", code3: "SLE", capital: "フリータウン", currency: "レオン", currencyCode: "SLE", currencySymbol: "Le" },
  "シンガポール": { en: "Singapore", code: "SG", code3: "SGP", capital: "シンガポール", currency: "シンガポール・ドル", currencyCode: "SGD", currencySymbol: "$" },
  "スロバキア": { en: "Slovakia", code: "SK", code3: "SVK", capital: "ブラチスラバ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "スロベニア": { en: "Slovenia", code: "SI", code3: "SVN", capital: "リュブリャナ", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ソロモン諸島": { en: "Solomon Islands", code: "SB", code3: "SLB", capital: "ホニアラ", currency: "ソロモン諸島・ドル", currencyCode: "SBD", currencySymbol: "$" },
  "ソマリア": { en: "Somalia", code: "SO", code3: "SOM", capital: "モガディシュ", currency: "ソマリア・シリング", currencyCode: "SOS", currencySymbol: "Sh" },
  "南アフリカ": { en: "South Africa", code: "ZA", code3: "ZAF", capital: "プレトリア", currency: "ランド", currencyCode: "ZAR", currencySymbol: "R" },
  "韓国": { en: "Republic of Korea", code: "KR", code3: "KOR", capital: "ソウル", currency: "韓国ウォン", currencyCode: "KRW", currencySymbol: "₩" },
  "南スーダン": { en: "South Sudan", code: "SS", code3: "SSD", capital: "ジュバ", currency: "南スーダン・ポンド", currencyCode: "SSP", currencySymbol: "£" },
  "スペイン": { en: "Spain", code: "ES", code3: "ESP", capital: "マドリード", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "スリランカ": { en: "Sri Lanka", code: "LK", code3: "LKA", capital: "スリジャヤワルダナプラコッテ", currency: "スリランカ・ルピー", currencyCode: "LKR", currencySymbol: "Rs" },
  "スーダン": { en: "Sudan", code: "SD", code3: "SDN", capital: "ハルツーム", currency: "スーダン・ポンド", currencyCode: "SDG", currencySymbol: "£" },
  "スリナム": { en: "Suriname", code: "SR", code3: "SUR", capital: "パラマリボ", currency: "スリナム・ドル", currencyCode: "SRD", currencySymbol: "$" },
  "スウェーデン": { en: "Sweden", code: "SE", code3: "SWE", capital: "ストックホルム", currency: "スウェーデン・クローナ", currencyCode: "SEK", currencySymbol: "kr" },
  "スイス": { en: "Switzerland", code: "CH", code3: "CHE", capital: "ベルン", currency: "スイス・フラン", currencyCode: "CHF", currencySymbol: "Fr" },
  "シリア": { en: "Syria", code: "SY", code3: "SYR", capital: "ダマスカス", currency: "シリア・ポンド", currencyCode: "SYP", currencySymbol: "£" },
  "台湾": { en: "Taiwan", code: "TW", code3: "TWN", capital: "台北", currency: "新台湾ドル", currencyCode: "TWD", currencySymbol: "NT$" },
  "タジキスタン": { en: "Tajikistan", code: "TJ", code3: "TJK", capital: "ドゥシャンベ", currency: "ソモニ", currencyCode: "TJS", currencySymbol: "ЅМ" },
  "タンザニア": { en: "Tanzania", code: "TZ", code3: "TZA", capital: "ドドマ", currency: "タンザニア・シリング", currencyCode: "TZS", currencySymbol: "Sh" },
  "タイ": { en: "Thailand", code: "TH", code3: "THA", capital: "バンコク", currency: "バーツ", currencyCode: "THB", currencySymbol: "฿" },
  "東ティモール": { en: "Timor-Leste", code: "TL", code3: "TLS", capital: "ディリ", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "トーゴ": { en: "Togo", code: "TG", code3: "TGO", capital: "ロメ", currency: "CFAフラン", currencyCode: "XOF", currencySymbol: "Fr" },
  "トンガ": { en: "Tonga", code: "TO", code3: "TON", capital: "ヌクアロファ", currency: "パアンガ", currencyCode: "TOP", currencySymbol: "T$" },
  "トリニダード・トバゴ": { en: "Trinidad and Tobago", code: "TT", code3: "TTO", capital: "ポートオブスペイン", currency: "トリニダード・トバゴ・ドル", currencyCode: "TTD", currencySymbol: "$" },
  "チュニジア": { en: "Tunisia", code: "TN", code3: "TUN", capital: "チュニス", currency: "チュニジア・ディナール", currencyCode: "TND", currencySymbol: "د.ت" },
  "トルコ": { en: "Turkey", code: "TR", code3: "TUR", capital: "アンカラ", currency: "トルコリラ", currencyCode: "TRY", currencySymbol: "₺" },
  "トルクメニスタン": { en: "Turkmenistan", code: "TM", code3: "TKM", capital: "アシガバット", currency: "マナト", currencyCode: "TMT", currencySymbol: "m" },
  "ツバル": { en: "Tuvalu", code: "TV", code3: "TUV", capital: "フナフティ", currency: "オーストラリア・ドル", currencyCode: "AUD", currencySymbol: "$" },
  "ウガンダ": { en: "Uganda", code: "UG", code3: "UGA", capital: "カンパラ", currency: "ウガンダ・シリング", currencyCode: "UGX", currencySymbol: "Sh" },
  "ウクライナ": { en: "Ukraine", code: "UA", code3: "UKR", capital: "キーウ", currency: "フリヴニャ", currencyCode: "UAH", currencySymbol: "₴" },
  "アラブ首長国連邦": { en: "United Arab Emirates", code: "AE", code3: "ARE", capital: "アブダビ", currency: "UAEディルハム", currencyCode: "AED", currencySymbol: "د.إ" },
  "イギリス": { en: "United Kingdom", code: "GB", code3: "GBR", capital: "ロンドン", currency: "イギリスポンド", currencyCode: "GBP", currencySymbol: "£" },
  "アメリカ合衆国": { en: "United States", code: "US", code3: "USA", capital: "ワシントンD.C.", currency: "USドル", currencyCode: "USD", currencySymbol: "$" },
  "ウルグアイ": { en: "Uruguay", code: "UY", code3: "URY", capital: "モンテビデオ", currency: "ウルグアイ・ペソ", currencyCode: "UYU", currencySymbol: "$" },
  "ウズベキスタン": { en: "Uzbekistan", code: "UZ", code3: "UZB", capital: "タシケント", currency: "スム", currencyCode: "UZS", currencySymbol: "с" },
  "バヌアツ": { en: "Vanuatu", code: "VU", code3: "VUT", capital: "ポートビラ", currency: "バツ", currencyCode: "VUV", currencySymbol: "Vt" },
  "バチカン市国": { en: "Vatican City", code: "VA", code3: "VAT", capital: "バチカン市国", currency: "ユーロ", currencyCode: "EUR", currencySymbol: "€" },
  "ベネズエラ": { en: "Venezuela", code: "VE", code3: "VEN", capital: "カラカス", currency: "ボリバル・ソベラノ", currencyCode: "VES", currencySymbol: "Bs.S" },
  "ベトナム": { en: "Vietnam", code: "VN", code3: "VNM", capital: "ハノイ", currency: "ドン", currencyCode: "VND", currencySymbol: "₫" },
  "イエメン": { en: "Yemen", code: "YE", code3: "YEM", capital: "サヌア", currency: "イエメン・リアル", currencyCode: "YER", currencySymbol: "﷼" },
  "ザンビア": { en: "Zambia", code: "ZM", code3: "ZMB", capital: "ルサカ", currency: "ザンビア・クワチャ", currencyCode: "ZMW", currencySymbol: "ZK" },
  "ジンバブエ": { en: "Zimbabwe", code: "ZW", code3: "ZWE", capital: "ハラレ", currency: "ジンバブエ・ドル", currencyCode: "ZWL", currencySymbol: "$" }
};

const japaneseCountry = $input.first().json['国名（日本語）'];
const entry = countryMap[japaneseCountry];

if (!entry) {
  throw new Error(`国名変換できませんでした: ${japaneseCountry}`);
}

const getRegion = (code3) => {
  const asia = ["AFG", "BGD", "BTN", "BRN", "KHM", "CHN", "IND", "IDN", "JPN", "KAZ", "KGZ", "LAO", "MYS", "MDV", "MNG", "MMR", "NPL", "PAK", "PHL", "SGP", "KOR", "LKA", "TWN", "TJK", "THA", "TLS", "UZB", "VNM"];
  const middleEast = ["BHR", "IRN", "IRQ", "ISR", "JOR", "KWT", "LBN", "OMN", "QAT", "SAU", "SYR", "TUR", "ARE", "YEM"];
  const europe = ["ALB", "AND", "ARM", "AUT", "AZE", "BLR", "BEL", "BIH", "BGR", "HRV", "CYP", "CZE", "DNK", "EST", "FIN", "FRA", "GEO", "DEU", "GRC", "HUN", "ISL", "IRL", "ITA", "LVA", "LIE", "LTU", "LUX", "MLT", "MDA", "MCO", "MNE", "NLD", "MKD", "NOR", "POL", "PRT", "ROU", "RUS", "SMR", "SRB", "SVK", "SVN", "ESP", "SWE", "CHE", "UKR", "GBR", "VAT"];
  const africa = ["DZA", "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COM", "COG", "COD", "CIV", "DJI", "EGY", "GNQ", "ERI", "SWZ", "ETH", "GAB", "GMB", "GHA", "GIN", "GNB", "KEN", "LSO", "LBR", "LBY", "MDG", "MWI", "MLI", "MRT", "MUS", "MAR", "MOZ", "NAM", "NER", "NGA", "RWA", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN", "TZA", "TGO", "TUN", "UGA", "ESH", "ZMB", "ZWE"];
  const oceania = ["AUS", "FJI", "KIR", "MHL", "FSM", "NRU", "NZL", "PLW", "PNG", "WSM", "SLB", "TON", "TUV", "VUT"];
  const northAmerica = ["ATG", "BHS", "BRB", "BLZ", "CAN", "CRC", "CUB", "DMA", "DOM", "SLV", "GRD", "GTM", "HTI", "HND", "JAM", "MEX", "NIC", "PAN", "KNA", "LCA", "VCT", "USA"];
  const southAmerica = ["ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUY", "PRY", "PER", "SUR", "URY", "VEN"];

  if (middleEast.includes(code3)) return "中東";
  if (asia.includes(code3)) return "アジア";
  if (europe.includes(code3)) return "ヨーロッパ";
  if (africa.includes(code3)) return "アフリカ";
  if (oceania.includes(code3)) return "オセアニア";
  if (northAmerica.includes(code3)) return "北米";
  if (southAmerica.includes(code3)) return "南米";
  return "その他";
};

const countryRegion = getRegion(entry.code3 || "");

return [{
  json: {
    country: japaneseCountry,
    countryEn: entry.en,
    countryCode: entry.code,
    code3: entry.code3 || "",
    capital: entry.capital || "",
    isJapan: entry.isJapan === true,
    currency: entry.currency || "",
    currencyCode: entry.currencyCode || "",
    currencySymbol: entry.currencySymbol || "",
    region: countryRegion,
    "地域": countryRegion
  }
}];